plugins {
    id 'org.gradle.toolchains.foojay-resolver-convention' version '0.9.0'
}

rootProject.name = 'pdfg2d'

includeBuild 'F:/dev/zamasoftnet-public/zstream'

include 'pdfg2d-font'
include 'pdfg2d-core'
include 'pdfg2d-pdf'
include 'pdfg2d-svg'
include 'pdfg2d-svg-emoji'
include 'pdfg2d-demo'
