description = 'Simple graphic context'

dependencies {
    implementation 'net.zamasoft:zstream-resolver:1.0.0-SNAPSHOT'
    implementation project(':pdfg2d-font')
    implementation 'net.zamasoft:zstream-io:1.0.0-SNAPSHOT'
}

publishing {
    publications {
        maven(MavenPublication) {
            pom {
                description = 'Simple graphic context'
                url = 'https://github.com/mimidesunya/pdfg2d/tree/main/pdfg2d-core'
                
                scm {
                    connection = 'scm:git:https://github.com/mimidesunya/pdfg2d/tree/main/pdfg2d-core'
                    developerConnection = 'scm:git:https://github.com/mimidesunya/pdfg2d/tree/main/pdfg2d-core'
                    url = 'https://github.com/mimidesunya/pdfg2d/tree/main/pdfg2d-core'
                }
            }
        }
    }
}
