description = 'PDF output implementation'

dependencies {
    implementation project(':pdfg2d-core')
    implementation 'net.zamasoft:zstream-resolver:1.0.0-SNAPSHOT'
    implementation 'net.zamasoft:zstream-io:1.0.0-SNAPSHOT'
    implementation project(':pdfg2d-font')
    implementation 'org.apache.xmlgraphics:batik-gvt:1.19'
    implementation 'com.twelvemonkeys.imageio:imageio-jpeg:3.13.1'
    implementation 'com.drewnoakes:metadata-extractor:2.20.0'
}

publishing {
    publications {
        maven(MavenPublication) {
            pom {
                description = 'PDF output implementation'
                url = 'https://github.com/mimidesunya/pdfg2d/tree/main/pdfg2d-pdf'
                
                scm {
                    connection = 'scm:git:https://github.com/mimidesunya/pdfg2d/tree/main/pdfg2d-pdf'
                    developerConnection = 'scm:git:https://github.com/mimidesunya/pdfg2d/tree/main/pdfg2d-pdf'
                    url = 'https://github.com/mimidesunya/pdfg2d/tree/main/pdfg2d-pdf'
                }
            }
        }
    }
}
